import { ATTRIBUTE_ENDPOINTS } from '@/services/thuocTinhService'

export const ATTRIBUTE_PAGE_CONFIGS = {
  DANH_MUC: {
    endpoint: ATTRIBUTE_ENDPOINTS.DANH_MUC,
    listRouteName: 'AdminAttrCategoryList',
    createRouteName: 'AdminAttrCategoryCreate',
    editRouteName: 'AdminAttrCategoryEdit',
    title: 'Danh Mục',
    subtitle: 'Nhóm phân loại chính của sản phẩm, dùng để lọc và tổ chức catalog trên admin.',
    itemLabel: 'danh mục',
    searchPlaceholder: 'Tìm theo mã danh mục hoặc tên danh mục...',
  },
  THUONG_HIEU: {
    endpoint: ATTRIBUTE_ENDPOINTS.THUONG_HIEU,
    listRouteName: 'AdminAttrBrandsList',
    createRouteName: 'AdminAttrBrandsCreate',
    editRouteName: 'AdminAttrBrandsEdit',
    title: 'Thương Hiệu',
    subtitle: 'Quản lý danh sách thương hiệu để gắn cho sản phẩm chạy bộ.',
    itemLabel: 'thương hiệu',
    searchPlaceholder: 'Tìm theo mã thương hiệu hoặc tên thương hiệu...',
  },
  XUAT_XU: {
    endpoint: ATTRIBUTE_ENDPOINTS.XUAT_XU,
    listRouteName: 'AdminAttrOriginsList',
    createRouteName: 'AdminAttrOriginsCreate',
    editRouteName: 'AdminAttrOriginsEdit',
    title: 'Xuất Xứ',
    subtitle: 'Thuộc tính nguồn gốc sản phẩm, hiển thị ở thông tin chính của sản phẩm.',
    itemLabel: 'xuất xứ',
    searchPlaceholder: 'Tìm theo mã xuất xứ hoặc tên xuất xứ...',
  },
  MUC_DICH_CHAY: {
    endpoint: ATTRIBUTE_ENDPOINTS.MUC_DICH_CHAY,
    listRouteName: 'AdminAttrRunningPurposesList',
    createRouteName: 'AdminAttrRunningPurposesCreate',
    editRouteName: 'AdminAttrRunningPurposesEdit',
    title: 'Mục Đích Chạy',
    subtitle: 'Phân loại mục đích sử dụng như daily training, race day, trail hay recovery.',
    itemLabel: 'mục đích chạy',
    searchPlaceholder: 'Tìm theo mã mục đích chạy hoặc tên mục đích...',
  },
  CHAT_LIEU: {
    endpoint: ATTRIBUTE_ENDPOINTS.CHAT_LIEU,
    listRouteName: 'AdminAttrMaterialsList',
    createRouteName: 'AdminAttrMaterialsCreate',
    editRouteName: 'AdminAttrMaterialsEdit',
    title: 'Chất Liệu',
    subtitle: 'Thuộc tính chất liệu upper hoặc vật liệu chính gắn trực tiếp lên sản phẩm.',
    itemLabel: 'chất liệu',
    searchPlaceholder: 'Tìm theo mã chất liệu hoặc tên chất liệu...',
  },
  DE_GIAY: {
    endpoint: ATTRIBUTE_ENDPOINTS.DE_GIAY,
    listRouteName: 'AdminAttrSoleTypesList',
    createRouteName: 'AdminAttrSoleTypesCreate',
    editRouteName: 'AdminAttrSoleTypesEdit',
    title: 'Đế Giày',
    subtitle: 'Quản lý kiểu đế hoặc loại outsole/midsole gắn cho sản phẩm.',
    itemLabel: 'đế giày',
    searchPlaceholder: 'Tìm theo mã đế giày hoặc tên đế giày...',
  },
  CO_GIAY: {
    endpoint: ATTRIBUTE_ENDPOINTS.CO_GIAY,
    listRouteName: 'AdminAttrCollarTypesList',
    createRouteName: 'AdminAttrCollarTypesCreate',
    editRouteName: 'AdminAttrCollarTypesEdit',
    title: 'Cổ Giày',
    subtitle: 'Thuộc tính mô tả chiều cao hoặc kiểu cổ giày của từng sản phẩm.',
    itemLabel: 'cổ giày',
    searchPlaceholder: 'Tìm theo mã cổ giày hoặc tên cổ giày...',
    extraField: {
      label: 'Giá trị chi tiết',
      placeholder: 'Low / Mid / High',
      hint: 'Dùng để mô tả sâu hơn cho cổ giày khi hiển thị ở admin.',
      tableLabel: 'Giá trị',
    },
  },
  MAU_SAC: {
    endpoint: ATTRIBUTE_ENDPOINTS.MAU_SAC,
    listRouteName: 'AdminAttrColorsList',
    createRouteName: 'AdminAttrColorsCreate',
    editRouteName: 'AdminAttrColorsEdit',
    title: 'Màu Sắc',
    subtitle: 'Thuộc tính của biến thể sản phẩm, dùng để tạo SKU theo màu.',
    itemLabel: 'màu sắc',
    searchPlaceholder: 'Tìm theo mã màu sắc hoặc tên màu sắc...',
    extraField: {
      label: 'Mã màu HEX',
      placeholder: '#0EA5E9',
      hint: 'Mã màu dùng để hiển thị chấm màu trong biến thể sản phẩm.',
      tableLabel: 'HEX',
      type: 'color',
    },
  },
  KICH_THUOC: {
    endpoint: ATTRIBUTE_ENDPOINTS.KICH_THUOC,
    listRouteName: 'AdminAttrSizesList',
    createRouteName: 'AdminAttrSizesCreate',
    editRouteName: 'AdminAttrSizesEdit',
    title: 'Kích Thước',
    subtitle: 'Thuộc tính của biến thể sản phẩm, dùng để quản lý size bán hàng.',
    itemLabel: 'kích thước',
    searchPlaceholder: 'Tìm theo mã kích thước hoặc tên kích thước...',
    extraField: {
      label: 'Giá trị size',
      placeholder: '40 / EU 40 / US 8',
      hint: 'Có thể lưu format size chuẩn để đồng bộ với biến thể và tồn kho.',
      tableLabel: 'Giá trị',
    },
  },
}

export default ATTRIBUTE_PAGE_CONFIGS
