# .github/dependabot.yml
version: 2
updates:
  # Maintain dependencies for the Java Backend (Gradle)
  - package-ecosystem: "gradle"
    directory: "/BE"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      backend-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for the Vue Frontend (npm)
  - package-ecosystem: "npm"
    directory: "/FE"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1

