export const db = {
  // Product Master Data
  categories: [
    { id: "D-001", name: "Giày chạy bộ", status: "ACTIVE" },
    { id: "D-002", name: "Giày thể thao", status: "ACTIVE" },
    { id: "D-003", name: "Giày casual", status: "ACTIVE" },
    { id: "D-004", name: "Giày bóng rổ", status: "ACTIVE" },
  ],

  brands: [
    { id: "TH-001", name: "AeroStride", status: "ACTIVE" },
    { id: "TH-002", name: "Nike", status: "ACTIVE" },
    { id: "TH-003", name: "Adidas", status: "ACTIVE" },
    { id: "TH-004", name: "Puma", status: "ACTIVE" },
  ],

  origins: [
    { id: "XX-001", name: "Việt Nam", status: "ACTIVE" },
    { id: "XX-002", name: "Trung Quốc", status: "ACTIVE" },
    { id: "XX-003", name: "Nhật Bản", status: "ACTIVE" },
    { id: "XX-004", name: "Hàn Quốc", status: "ACTIVE" },
  ],

  purposes: [
    { id: "MD-001", name: "Chạy dài", status: "ACTIVE" },
    { id: "MD-002", name: "Chạy nhanh", status: "ACTIVE" },
    { id: "MD-003", name: "Thể thao hằng ngày", status: "ACTIVE" },
    { id: "MD-004", name: "Đi bộ", status: "ACTIVE" },
  ],

  shoeParts: [
    { id: "CG-001", name: "Cổ cao", status: "ACTIVE" },
    { id: "CG-002", name: "Cổ trung bình", status: "ACTIVE" },
    { id: "CG-003", name: "Cổ thấp", status: "ACTIVE" },
  ],

  materials: [
    { id: "CL-001", name: "Vải tổng hợp", status: "ACTIVE" },
    { id: "CL-002", name: "Da thật", status: "ACTIVE" },
    { id: "CL-003", name: "Da nhân tạo", status: "ACTIVE" },
    { id: "CL-004", name: "Lưới thoáng khí", status: "ACTIVE" },
  ],

  soleCosts: [
    { id: "DE-001", name: "Cao su", status: "ACTIVE" },
    { id: "DE-002", name: "Foam", status: "ACTIVE" },
    { id: "DE-003", name: "Eva", status: "ACTIVE" },
    { id: "DE-004", name: "Hybrid", status: "ACTIVE" },
  ],

  vouchers: [
    {
      id: "1",
      ma: "V01",
      ten: "Giảm 10%",
      loaiPhieu: "PERCENT",
      phanTramGiamGia: 10,
      soTienGiam: null,
      soLuong: 100,
      donHangToiThieu: 500000,
      giamToiDa: 200000,
      ngayBatDau: 1772323200000,
      ngayKetThuc: 1798675200000,
      ghiChu: "Áp dụng toàn hệ thống",
      status: "ACTIVE",
    },
  ],

  products: [
    {
      id: 101,
      sku: "SH-001",
      name: "Aero Runner",
      brand: "AeroStride",
      category: "Giày chạy bộ",
      qty: 48,
      price: 1290000,
      status: "ACTIVE",
      createdAt: "2026-03-20",
    },
    {
      id: 102,
      sku: "SH-002",
      name: "Street Nova",
      brand: "AeroStride",
      category: "Giày thể thao",
      qty: 32,
      price: 990000,
      status: "ACTIVE",
      createdAt: "2026-03-22",
    },
  ],

  sales: [
    {
      id: 1,
      code: "SALE-001",
      name: "Phiên bán hàng #1",
      status: "ACTIVE",
      createdAt: "2026-04-01",
      note: "",
    },
  ],
  orders: [
    {
      id: 1,
      code: "HD-0001",
      customer: "Nguyễn Văn A",
      email: "nguyenvana@gmail.com",
      phone: "0912345001",
      invoiceType: "offline",
      employeeCode: "NV-001",
      total: 1990000,
      status: "COMPLETED",
      createdAt: "2026-04-02T10:30:00",
      paymentMethodCode: "PT001",
      paymentMethodName: "Tiền mặt",
      paymentType: "CASH",
      items: [
        {
          productName: "Aero Runner",
          qty: 1,
          unitPrice: 1290000,
          discount: 0,
          total: 1290000,
        },
        {
          productName: "Street Nova",
          qty: 1,
          unitPrice: 990000,
          discount: 150000,
          total: 840000,
        },
      ],
      paymentMethod: "Tiền mặt",
      address: "Số 12, ngõ 8 Lê Đức Thọ, Mỹ Đình 1, Nam Từ Liêm, Hà Nội",
    },
    {
      id: 2,
      code: "HD-0002",
      customer: "Trần Thị B",
      email: "tranthib@gmail.com",
      phone: "0912345002",
      invoiceType: "online",
      employeeCode: "NV-002",
      total: 2450000,
      status: "CONFIRMED",
      createdAt: "2026-04-03T14:15:00",
      paymentMethodCode: "PT002",
      paymentMethodName: "Chuyển khoản Ngân hàng",
      paymentType: "TRANSFER",
      items: [
        {
          productName: "Aero Runner",
          qty: 2,
          unitPrice: 1290000,
          discount: 130000,
          total: 2450000,
        },
      ],
      paymentMethod: "Chuyển khoản",
      address: "18 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM",
      recipientName: "Trần Thị B",
      recipientPhone: "0911222333",
      shippingMethod: "Giao hàng tiêu chuẩn",
    },
    {
      id: 3,
      code: "HD-0003",
      customer: "Lê Văn C",
      email: "",
      phone: "0912345003",
      invoiceType: "offline",
      employeeCode: "NV-001",
      total: 1680000,
      status: "COMPLETED",
      createdAt: "2026-04-04T09:45:00",
      paymentMethodCode: "PT001",
      paymentMethodName: "Tiền mặt",
      paymentType: "CASH",
      items: [
        {
          productName: "Street Nova",
          qty: 2,
          unitPrice: 990000,
          discount: 300000,
          total: 1680000,
        },
      ],
      paymentMethod: "Tiền mặt",
      address: "22 Trần Thái Tông, Dịch Vọng, Cầu Giấy, Hà Nội",
    },
    {
      id: 4,
      code: "HD-0004",
      customer: "Phạm Thị D",
      email: "phamthid@gmail.com",
      phone: "0912345004",
      invoiceType: "online",
      employeeCode: "NV-003",
      total: 3120000,
      status: "CONFIRMED",
      createdAt: "2026-04-05T11:20:00",
      paymentMethodCode: "PT003",
      paymentMethodName: "Ví điện tử MoMo",
      paymentType: "WALLET",
      items: [
        {
          productName: "Aero Runner",
          qty: 1,
          unitPrice: 1290000,
          discount: 0,
          total: 1290000,
        },
        {
          productName: "Street Nova",
          qty: 1,
          unitPrice: 990000,
          discount: 0,
          total: 990000,
        },
      ],
      paymentMethod: "Ví điện tử",
      address: "123 Lê Lợi, Phường Bến Thành, Quận 1, TP.HCM",
      recipientName: "Phạm Thị D",
      recipientPhone: "0913445566",
      shippingMethod: "Giao hàng nhanh 24h",
    },
    {
      id: 5,
      code: "HD-0005",
      customer: "Hoàng Văn E",
      email: "",
      phone: "0912345005",
      invoiceType: "offline",
      employeeCode: "NV-002",
      total: 2790000,
      status: "COMPLETED",
      createdAt: "2026-04-06T15:30:00",
      paymentMethodCode: "PT001",
      paymentMethodName: "Tiền mặt",
      paymentType: "CASH",
      items: [
        {
          productName: "Aero Runner",
          qty: 2,
          unitPrice: 1290000,
          discount: 0,
          total: 2580000,
        },
        {
          productName: "Street Nova",
          qty: 1,
          unitPrice: 990000,
          discount: 780000,
          total: 210000,
        },
      ],
      paymentMethod: "Tiền mặt",
      address: "456 Hàm Nghi, Phường Đa Kao, Quận 1, TP.HCM",
    },
    {
      id: 6,
      code: "HD-0006",
      customer: "Nguyễn Thị F",
      email: "nguyenthif@gmail.com",
      phone: "0912345006",
      invoiceType: "online",
      employeeCode: "NV-001",
      total: 1540000,
      status: "CANCELED",
      createdAt: "2026-04-07T08:00:00",
      paymentMethodCode: "PT004",
      paymentMethodName: "Ví điện tử ZaloPay",
      paymentType: "WALLET",
      items: [
        {
          productName: "Street Nova",
          qty: 1,
          unitPrice: 990000,
          discount: 0,
          total: 990000,
        },
        {
          productName: "Aero Runner",
          qty: 1,
          unitPrice: 1290000,
          discount: 730000,
          total: 560000,
        },
      ],
      paymentMethod: "Chuyển khoản",
      address: "789 Nguyễn Thị Minh Khai, Phường Võ Thị Sáu, Quận 3, TP.HCM",
      recipientName: "Nguyễn Thị F",
      recipientPhone: "0914556677",
      shippingMethod: "Giao hàng tiêu chuẩn",
    },
    {
      id: 7,
      code: "HD-0007",
      customer: "Đặng Văn G",
      email: "",
      phone: "0912345007",
      invoiceType: "offline",
      employeeCode: "NV-003",
      total: 2210000,
      status: "COMPLETED",
      createdAt: "2026-04-08T16:45:00",
      paymentMethodCode: "PT005",
      paymentMethodName: "Thẻ tín dụng/Ghi nợ",
      paymentType: "CARD",
      items: [
        {
          productName: "Aero Runner",
          qty: 1,
          unitPrice: 1290000,
          discount: 0,
          total: 1290000,
        },
        {
          productName: "Street Nova",
          qty: 1,
          unitPrice: 990000,
          discount: 70000,
          total: 920000,
        },
      ],
      paymentMethod: "Thẻ tín dụng/Ghi nợ",
      address: "321 Cách Mạng Tháng Tám, Phường 6, Quận 3, TP.HCM",
    },
  ],
  attributes: [
    {
      id: 1,
      code: "SIZE-42",
      name: "Size 42",
      status: "ACTIVE",
      createdAt: "2026-03-10",
    },
  ],
  discounts: [
    {
      id: 1,
      ma: "DG-001",
      ten: "Đợt giảm giá tháng 4",
      loaiGiamGia: "PERCENT",
      soTienGiam: 15,
      dieuKienGiamGia: 1000000,
      ngayBatDau: 1772323200000,
      ngayKetThuc: 1774915200000,
      mucUuTien: 1,
    },
  ],
  customers: [
    {
      id: "1",
      ma: "KH-001",
      ten: "Nguyễn Văn A",
      email: "nguyenvana@gmail.com",
      tenTaiKhoan: "nguyenvana",
      gioiTinh: true,
      sdt: "0900000000",
      ngaySinh: "1998-01-10",
      hinhAnh: "",
      ghiChu: "Khách mua online thường xuyên",
      trangThai: "ACTIVE",
      ngayTao: 1767225600000,
      ngayCapNhat: 1775865600000,
      tinh: "Hà Nội",
      thanhPho: "Nam Từ Liêm",
      phuongXa: "Mỹ Đình 1",
      diaChiChiTiet: "Số 12, ngõ 8 Lê Đức Thọ",
      tenNguoiNhan: "Nguyễn Văn A",
      sdtNguoiNhan: "0900000000",
    },
    {
      id: "2",
      ma: "KH-002",
      ten: "Trần Thị B",
      email: "tranthib@gmail.com",
      tenTaiKhoan: "tranthib",
      gioiTinh: false,
      sdt: "0911222333",
      ngaySinh: "2000-07-21",
      hinhAnh: "",
      ghiChu: "Khách mua online, ưu tiên giao nhanh",
      trangThai: "ACTIVE",
      ngayTao: 1769817600000,
      ngayCapNhat: 1776297600000,
      tinh: "TP.HCM",
      thanhPho: "Quận 1",
      phuongXa: "Phường Bến Nghé",
      diaChiChiTiet: "18 Nguyễn Huệ",
      tenNguoiNhan: "Trần Thị B",
      sdtNguoiNhan: "0911222333",
    },
    {
      id: "3",
      ma: "KL-001",
      ten: "Lê Văn C",
      email: "",
      tenTaiKhoan: "",
      gioiTinh: true,
      sdt: "0988333444",
      ngaySinh: "1995-11-12",
      hinhAnh: "",
      ghiChu: "Khách lẻ mua trực tiếp tại quầy",
      trangThai: "ACTIVE",
      ngayTao: 1775606400000,
      ngayCapNhat: 1776038400000,
      tinh: "Hà Nội",
      thanhPho: "Cầu Giấy",
      phuongXa: "Dịch Vọng",
      diaChiChiTiet: "22 Trần Thái Tông",
      tenNguoiNhan: "Lê Văn C",
      sdtNguoiNhan: "0988333444",
      loaiKhachHang: "RETAIL",
    },
  ],
  employees: [
    {
      id: "1",
      ma: "NV-001",
      ten: "Trần Thị B",
      email: "admin@shop.com",
      tenTaiKhoan: "tranthib",
      gioiTinh: false,
      sdt: "0909888777",
      ngaySinh: "1998-05-20",
      hinhAnh: "",
      trangThai: "ACTIVE",
      ngayTao: 1767225600000,
      ngayCapNhat: 1775865600000,
      maPhanQuyen: "PQ-01",
      tenPhanQuyen: "Quản lý",
      quyenHan: "ADMIN",
    },
    {
      id: "2",
      ma: "NV-002",
      ten: "Nguyễn Văn D",
      email: "staff@shop.com",
      tenTaiKhoan: "nguyenvand",
      gioiTinh: true,
      sdt: "0912333444",
      ngaySinh: "2000-10-11",
      hinhAnh: "",
      trangThai: "ACTIVE",
      ngayTao: 1769817600000,
      ngayCapNhat: 1776297600000,
      maPhanQuyen: "PQ-02",
      tenPhanQuyen: "Nhân viên bán hàng",
      quyenHan: "STAFF",
    },
  ],
  payments: [
    {
      id: 1,
      transactionCode: "GD-20260412-001",
      customer: "Nguyễn Văn A",
      amount: 1290000,
      method: "Tiền mặt",
      paidAt: "2026-04-12",
      status: "SUCCESS",
    },
    {
      id: 2,
      transactionCode: "GD-20260412-002",
      customer: "Trần Thị B",
      amount: 2450000,
      method: "Chuyển khoản",
      paidAt: "2026-04-12",
      status: "UNPAID",
    },
    {
      id: 3,
      transactionCode: "GD-20260411-003",
      customer: "Lê Văn C",
      amount: 980000,
      method: "Ví điện tử",
      paidAt: "2026-04-11",
      status: "SUCCESS",
    },
  ],
  paymentMethods: [
    {
      id: "1",
      ma_phuong_thuc_thanh_toan: "PT001",
      ten_phuong_thuc_thanh_toan: "Tiền mặt",
      loaiThanhToan: "CASH",
    },
    {
      id: "2",
      ma_phuong_thuc_thanh_toan: "PT002",
      ten_phuong_thuc_thanh_toan: "Chuyển khoản Ngân hàng",
      loaiThanhToan: "TRANSFER",
    },
    {
      id: "3",
      ma_phuong_thuc_thanh_toan: "PT003",
      ten_phuong_thuc_thanh_toan: "Ví điện tử MoMo",
      loaiThanhToan: "WALLET",
    },
    {
      id: "4",
      ma_phuong_thuc_thanh_toan: "PT004",
      ten_phuong_thuc_thanh_toan: "Ví điện tử ZaloPay",
      loaiThanhToan: "WALLET",
    },
    {
      id: "5",
      ma_phuong_thuc_thanh_toan: "PT005",
      ten_phuong_thuc_thanh_toan: "Thẻ tín dụng/Ghi nợ",
      loaiThanhToan: "CARD",
    },
  ],
  files: [
    {
      id: 1,
      code: "F001",
      name: "shoe-1.png",
      url: "/uploads/shoe-1.png",
      status: "ACTIVE",
      createdAt: "2026-04-05",
      relatedEntityType: "LEGACY",
      relatedEntityId: "101",
      relatedEntityCode: "SH-001",
      relatedEntityName: "Aero Runner",
    },
  ],
};
