export const PATH = {
    DASHBOARD: '/admin/thong-ke',
    BAN_HANG: '/admin/ban-hang',
    SAN_PHAM: '/admin/san-pham',
    BIEN_THE_SAN_PHAM: '/admin/san-pham/bien-the',
    SAN_PHAM_FORM: '/admin/san-pham/form',
    KHACH_HANG: '/admin/khach-hang',
    KHACH_HANG_FORM: '/admin/khach-hang/form',
    KHACH_HANG_DETAIL: '/admin/khach-hang/detail',
    HOA_DON: '/admin/hoa-don',
    HOA_DON_CHI_TIET: '/admin/hoa-don/chi-tiet',
    NHAN_VIEN: '/admin/nhan-vien',
    NHAN_VIEN_FORM: '/admin/nhan-vien/form',
    NHAN_VIEN_DETAIL: '/admin/nhan-vien/detail',
    DOT_GIAM_GIA: '/admin/dot-giam-gia',
    DOT_GIAM_GIA_FORM: '/admin/dot-giam-gia/form',
    PHIEU_GIAM_GIA: '/admin/phieu-giam-gia',
    PHIEU_GIAM_GIA_FORM: '/admin/phieu-giam-gia/form',
    PHIEU_GIAM_GIA_DETAIL: '/admin/phieu-giam-gia/detail',
    THUOC_TINH: '/admin/thuoc-tinh',
    THANH_TOAN: '/admin/thanh-toan',
    THONG_KE: '/admin/thong-ke',
    LANDING: '/',
    // Auth
    LOGIN: '/user/login',
    REGISTER: '/user/register',
    FORGOT_PASSWORD: '/user/forgot-password',
    
    // Admin Auth
    ADMIN_LOGIN: '/admin/login',
    ADMIN_REGISTER: '/admin/register',
    ADMIN_FORGOT_PASSWORD: '/admin/forgot-password',
    
    LOGOUT: '/auth/logout',
    SHOES: '/shoes',
    QUAN_LY_CHAT: '/admin/quan-ly-chat',
    LICH_LAM_VIEC: '/admin/lich-lam-viec',
    LICH_CA_LAM: '/admin/lich-ca-lam',
    LICH_SU_HOAT_DONG: '/admin/lich-su-hoat-dong',
    PROFILE: '/profile',
    ORDERS: '/my-orders',
};
