export const PATH = {
    DASHBOARD: '/',
    BAN_HANG: '/ban-hang',
    SAN_PHAM: '/san-pham',
    BIEN_THE_SAN_PHAM: '/san-pham/bien-the',
    SAN_PHAM_FORM: '/san-pham/form',
    KHACH_HANG: '/khach-hang',
    KHACH_HANG_FORM: '/khach-hang/form',
    KHACH_HANG_DETAIL: '/khach-hang/detail',
    HOA_DON: '/hoa-don',
    HOA_DON_CHI_TIET: '/hoa-don/chi-tiet',
    NHAN_VIEN: '/nhan-vien',
    NHAN_VIEN_FORM: '/nhan-vien/form',
    NHAN_VIEN_DETAIL: '/nhan-vien/detail',
    DOT_GIAM_GIA: '/dot-giam-gia',
    DOT_GIAM_GIA_FORM: '/dot-giam-gia/form',
    PHIEU_GIAM_GIA: '/phieu-giam-gia',
    PHIEU_GIAM_GIA_FORM: '/phieu-giam-gia/form',
    THUOC_TINH: '/thuoc-tinh',
    THANH_TOAN: '/thanh-toan',
    THONG_KE: '/thong-ke',
    // Auth
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    LOGOUT: '/auth/logout',
};
